### ISSUE TITLE
JOSS: typos

### ISSUE THREAD

**Issue by grlee77** [IMTtugraz/PyQMRI#2]
Hello,

Please resolve the following typos in the JOSS manuscript.

manuscript:
    Algorithmic section:  Levenberg–Marquat -> Levenberg–Marquardt
    Figure 2 caption: coilsensitivity -> coil sensitivity

GitHub README:
    spelling:  grafical -> graphical

**Comment by MaierOli2010** [comment]
Thank you for pointing that out. Typos should be fixed by the latest commit.

**Comment by grlee77** [comment]
Thanks!
